# Generated by Django 5.0.2 on 2024-05-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
