# Generated by Django 5.0.2 on 2024-05-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
